DITL editor with editing and undo
andrews05/ResForge pull request #12
Opened 2024-02-10 15:07 UTC by uliwitness

2024-02-10 15:21 UTC, uliwitness commented
I had to bump minimum system version to build with Xcode 15, I think. If that's a problem, let me know how one does that these days, I'm mostly on iOS these days, where the app store makes backwards compatibility nigh-impossible anyway, so I haven't had to stay backwards compatible with any old SDKs in a while and have forgotten how to do that.

2024-02-10 15:23 UTC, uliwitness commented
Oh, and BTW -- I've replied to your e-mail. You don't have to reply right now, but a short confirmation you received it would be nice, so I know I don't have to try sending it from some other account.

2024-02-11 05:09 UTC, andrews05 reviewed
Hi Uli
Thanks for your work here!
I haven't found a reply from you yet, sorry (I even checked spam).

I've had a quick look at this and will have a closer look later but just have a couple of comments for now.
Also, would you mind changing indentation to spaces to match the existing code style?

2024-02-11 05:09 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DialogEditorWindowController.swift
> +				imgRep?.draw(in: self.bounds)
You should be able to use `resource.preview` here rather than replicating code from the image plugin.
```suggestion
				resource.preview {
					$0?.draw(in: self.bounds)
				}			
```

2024-02-11 05:09 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DialogEditorWindowController.swift
> +		self.scrollView.documentView?.clipsToBounds = true
Looks like `clipsToBounds` requires the macOS 14 SDK. It's not a property I'm familiar with, but is there another way to achieve what you need here?

2024-02-12 16:39 UTC, uliwitness commented
OK, I think I've fixed it all!

2024-02-12 19:54 UTC, uliwitness commented
(PS — I did the refactoring before the changes, so if you view just the changes after [7ec4e83](https://github.com/andrews05/ResForge/pull/12/commits/7ec4e83155118cf8425ffda42355856c4e613397), you should get an easy-to-tell change log compared to what you already had a look at. Only [3c5c481](https://github.com/andrews05/ResForge/pull/12/commits/3c5c481971f02fee7f41cccab5d0f658e8b4e0b8) was before the refactor.

2024-02-13 05:48 UTC, andrews05 requested changes
Looking good! I've left a few comments on some issues.

And some musings on possible future enhancements (no need to action these now):
- Retain selection on undo/redo of property change
- Clear document edited state when you undo back to the start
- Fit window to document size when opening
- Show bounds of selected item in the side panel (maybe as editable inputs)
  - Probably as x,y,w,h rather than t,l,b,r
- Find matching DLOG/ALRT and set document size from bounds
- Show numbered list of all the items

2024-02-13 05:48 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DITLDocumentView.swift
> +		var willChange = false
Should this be true initially? There doesn't appear to be anywhere it would otherwise get set to true.

2024-02-13 05:48 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DITLItem.swift
> +			b += 3;
I think these should be -= (otherwise the box will grow on save).
```suggestion
			r -= 3;
			b -= 3;
```

2024-02-13 05:48 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DITLItemView.swift
> +		if #available(macOS 14, *) { // If built w. macOS 14+ SDK, this defaults to false.
I'll verify this later but I think it will need to be `#if compiler(>=5.9)`. Or maybe both.
(This wouldn't be an issue if one of my dev machines wasn't so old 😄)

2024-02-13 05:48 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DITLItemView.swift
> +			textBox.origin.y -= (textBox.size.height - measuredSize.height) / 2
Since the views are all flipped, should this be +=?
```suggestion
			textBox.origin.y += (textBox.size.height - measuredSize.height) / 2
```

2024-02-13 05:48 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DITLItemView.swift
> +			title.draw(at: NSZeroPoint, withAttributes: [.foregroundColor: NSColor.systemBlue, .font: NSFontManager.shared.font(withFamily: "Silom", traits: [], weight: 0, size: 12.0)!])
User items shouldn't have titles, right?

2024-02-13 05:48 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DialogEditorWindowController.swift
> +
We should make sure the undo stack is cleared here.

2024-02-13 05:48 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DITLItem.swift
> +		}
Need to check alignment byte after writing here.

2024-02-13 05:48 UTC, andrews05 commented on ResForge/Template Editor/Templates.rsrc
Looks like this includes resources from the NovaTools templates file, which can be deleted.
Since it only contains icons, it might be better to rename it to "Icons.rsrc".

2024-02-13 05:48 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DITLDocumentView.swift
> +	public override var isFlipped: Bool {
It would be helpful if you could switch indentation to spaces to match RF's existing code style.

2024-02-14 16:50 UTC, uliwitness commented on Plug-Ins/Dialog Editor/DITLDocumentView.swift
> +		var willChange = false
Ooops, the variable is not needed. Fixed.

2024-02-14 17:10 UTC, uliwitness commented on Plug-Ins/Dialog Editor/DITLItemView.swift
> +			title.draw(at: NSZeroPoint, withAttributes: [.foregroundColor: NSColor.systemBlue, .font: NSFontManager.shared.font(withFamily: "Silom", traits: [], weight: 0, size: 12.0)!])
Theoretically this byte should be zero, but I've seen DITLs that accidentally had them, so I thought I'd leave it in there.

2024-02-14 17:32 UTC, uliwitness commented
> * Retain selection on undo/redo of property change

Yeah, I saw that, but in the end it seemed too much effort for a functionality nobody will probably ever use 😅 I mean, the whole concept of a DITL editor on OS X doesn't really have a use case, but I've done lots of editors like this before and wanted a nice preview of windows.

> * Clear document edited state when you undo back to the start

Yeah, I don't remember at all how one did that.

> * Fit window to document size when opening

Yeah, seemed a bit too involved to do without risking that any "revert" or so would cause the window size to change. But would be a good idea. Maybe if I get bored someday.

> * Show bounds of selected item in the side panel (maybe as editable inputs)
>   * Probably as x,y,w,h rather than t,l,b,r

I actually meant to do that and forgot. Maybe if I get bored someday I'll do that pull request.

> * Find matching DLOG/ALRT and set document size from bounds

Yeah, I didn't want to do too much right now that involves other resources, but couldn't resist the ICON/PICT items because most dialogs just don't look right without those.

> * Show numbered list of all the items

Yeah, would make sense especially for help items. ResEdit also had a "badge items with their number" function, which is really handy since all coding with Dialog Manager keys off item numbers.

2024-02-15 04:13 UTC, andrews05 approved these changes
Awesome, thank you so much!

And yeah, I totally get what you mean about functionality nobody will probably ever use, which has certainly been one of the reasons I haven't made more editors myself 😄 
That said, there has been interest in a DITL editor from EV Nova modders, so your work here will not go unappreciated.

Just for interest, here's the only other DITL editor I've seen besides ResEdit's, from another Nova editor called MissionComputer. (The numbering should start at 1, and it doesn't recognise help items*, but it worked well enough) 
![Screen Shot 2024-02-15 at 5 09 52 PM](https://github.com/andrews05/ResForge/assets/4584038/bad7d021-a942-4e57-8087-6a2ed4a759bd)

(*I also realise I neglected help items when I updated the DITL template recently - I'll have to add that in)

2024-02-15 04:17 UTC, andrews05 commented on Plug-Ins/Dialog Editor/DITLItemView.swift
> +		if #available(macOS 14, *) { // If built w. macOS 14+ SDK, this defaults to false.
I've confirmed this is a compiler/SDK restriction, not a runtime issue. I'll change this after merge.

I'll just need to make sure I don't do release builds on my older computer.

2024-02-15 04:17 UTC, merged